[book]
title = "Packager-rs Guide"
authors = ["Alex Joss"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/jossware/pkg-rs"
edit-url-template = "https://github.com/jossware/pkg-rs/edit/main/docs/{path}"
